apps:
  vars:
    ansible_ssh_private_key_file: /home/vagrant/.ssh/id_rsa
  hosts:
    controlplane:
      ansible_host: 192.168.56.11
    node01:
      ansible_host: 192.168.56.21
    node02:
      ansible_host: 192.168.56.22